### ISSUE TITLE
Can’t set the volume in Fidelio A3

### ISSUE THREAD

**Issue by scarpita88** [mlaurijsse/homebridge-fidelio#2]
Pls help me. I Can’t manage the volume, I can only set power on/off my device AW3000.
I receive only the warning “alsa module not found disabling alsa”.
I can’t set the volume slider on homekit but only a switch. I really would have the possibility to manage volume (mid loud high) directly from homekit instead of this link https://host:8889/mp3link channel (aux in channel).
I’ve viewed the code but I don’t understand the part of making volume characteristic after the power fuction set.
I don’t use the external file config for volume and channel and I’ve tried both alsa true and false in my config.json
Do you have any suggestions for me??? Many many thanks for your support!!
Simone

**Comment by mlaurijsse** [comment]
Hi Simone,

I'm assuming you are using the native Home app to control your speaker. Unfortunately Apple doesn't support volume control via this app or Siri. See also: https://github.com/KhaosT/HAP-NodeJS/issues/452

Two alternatives:
- Use another, third party, homekit app. Plenty out there, so far all seem to support the volume control
- Make your speakers appear as either Lightbulb or Fan type of service. This way you can control volume by changing Brightness/RotationalSpeed. I just updated the code to support this.

Hope this solves your problem. Let me know if you need further assistance. 

Regards,

Marcel

**Comment by scarpita88** [comment]
Hi Marcel,

many thanks for the reply!
Do you have updated the plugin right now? Because actually If I set my speaker as a bulb or a fan I can only switch on/off.
Can you share all the options available in the config.json?
I will update the plugin on my raspberry homebridge soon and I will provide you a feedback.
Regards,
Simone

**Comment by scarpita88** [comment]
I confirm, now it works configured as a “fan”!
Thank you!
